### ISSUE TITLE
Prep course Rspec install command is incorrect

### ISSUE THREAD

**Issue by rdcsg** [CraftAcademy/ca_course#50]
In the course mtrl the file to create before installing Rspec contains a command with dbl quotes that should be single quotes.

The course mtr says it should be:

_# Gemfile
source "https://rubygems.org"

gem "rspec"_

But the install cmd only works if the gem statements gives the argument with single quotes like

_# Gemfile
source "https://rubygems.org"

gem 'rspec'_

**Comment by diraulo** [comment]
@rdcsg the use of single/double quotes in the `Gemfile` doesn't affect `Bundler` when installing gems 

`gem "rspec"` or `gem "rspec"` doesn't make any difference. If you had an error while running `bundle install` it was probably due to something else and not the double quotes.

The use of single/double quotes here is purely a matter of preference. I personally always use single quotes unless I have to use doubles quotes.

**Comment by rdcsg** [comment]
Thank you!  =)



Kind regards / Med vänliga hälsningar,
Rodrigo Muñoz,
Business Catalyst

RDCS Growth & Development
0768 633 697 <tel:0768%20633%20697>
rodrigo@rdcs.se <mailto:rodrigo@rdcs.se>



Den 2016-06-18 kl. 17:39, skrev Raoul DIFFOUO:
