### ISSUE TITLE
Where to create rspec lib?

### ISSUE THREAD

**Issue by rdcsg** [CraftAcademy/ca_course#51]
http://class.craftacademy.se/courses/course-v1:CraftAcademy+CA-101+20016-3/courseware/5a2bb7253cab4225b44388b5527d8071/750195582cde42cd97a6fb06eb0c6ba2/

The material talks about adding a dir called lib. But where should it be created? Inside the spec folder? Next to the spec folder?

Is it true that the "./" in the require statement means "start looking in the main project folder and work your way down from there"?

And why is it suddenly called a folder?

**Comment by diraulo** [comment]
Thanks @rdcsg for this -- Since it's the student's first encounter with Rspec during the course, we should probably be more clear about where to create the `lib` folder. We'll take care of that :wink:

Also, as I'm sure you've noticed by now we'll use the terms `directory` and `folder` interchangeably throughout the course. Sorry for any confusion it may have caused you.

**Comment by diraulo** [comment]
So I just revisited that section of the course material, and if the students follow the instructions they should be in the right folder when creating the `lib` folder. Will close this for now. Feel free to re-open if this is still an issue
